"""Very small ARI mock for the public SEGB demo."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone

from rdflib import URIRef

from segb_logger import ActivityKind, SemanticSEGBLogger


@dataclass(slots=True)
class AriMockResult:
    """Semantic artifacts generated by ARI for one human utterance."""

    shared_event_uri: URIRef
    listening_activity_uri: URIRef
    observation_message_uri: URIRef
    decision_activity_uri: URIRef
    response_message_uri: URIRef


def ari_handle_human_utterance(
    *,
    logger: SemanticSEGBLogger,
    human_uri: URIRef,
    text: str,
    observed_at: datetime,
) -> AriMockResult:
    """Logs ARI behavior: listen -> decide -> respond."""
    shared_event_uri = logger.get_shared_event_uri(
        event_kind="human_utterance",
        observed_at=observed_at,
        subject=human_uri,
        text=text,
        modality="speech",
    )

    listening_activity_uri = logger.log_activity(
        activity_id="ari_listening_1",
        activity_kind=ActivityKind.LISTENING,
        started_at=observed_at,
        ended_at=datetime.now(timezone.utc),
        related_shared_events=[shared_event_uri],
    )

    observation_message_uri = logger.log_message(
        text,
        message_id="ari_heard_1",
        generated_by_activity=listening_activity_uri,
        message_types=["oro:InitialMessage"],
    )
    logger.link_observation_to_shared_event(observation_message_uri, shared_event_uri, confidence=0.95)

    decision_activity_uri = logger.log_activity(
        activity_id="ari_decision_1",
        activity_kind=ActivityKind.DECISION,
        started_at=datetime.now(timezone.utc),
        triggered_by_activity=listening_activity_uri,
        triggered_by_entity=observation_message_uri,
        related_shared_events=[shared_event_uri],
        used_entities=[observation_message_uri],
    )
    response_message_uri = logger.log_message(
        "Maria, I heard you. I can help with climate news.",
        message_id="ari_response_1",
        generated_by_activity=decision_activity_uri,
        message_types=["oro:ResponseMessage"],
        previous_message=observation_message_uri,
    )

    return AriMockResult(
        shared_event_uri=shared_event_uri,
        listening_activity_uri=listening_activity_uri,
        observation_message_uri=observation_message_uri,
        decision_activity_uri=decision_activity_uri,
        response_message_uri=response_message_uri,
    )
