"""Simple and formal SEGB demo: ARI + TIAGo + one shared event."""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from rdflib import Graph, URIRef

if __package__ is None or __package__ == "":
    # Script mode (`python examples/run_simulation.py`): ensure project root is importable.
    project_root = Path(__file__).resolve().parents[1]
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))

    from segb_logger import SEGBPublisher, SemanticSEGBLogger, SharedEventPolicy
    from examples.ari_mock import AriMockResult, ari_handle_human_utterance
    from examples.tiago_mock import TiagoMockResult, tiago_handle_human_utterance
else:
    # Module mode (`python -m examples.run_simulation`).
    from segb_logger import SEGBPublisher, SemanticSEGBLogger, SharedEventPolicy
    from .ari_mock import AriMockResult, ari_handle_human_utterance
    from .tiago_mock import TiagoMockResult, tiago_handle_human_utterance

ARI_NAMESPACE = "https://gsi.upm.es/segb/robots/ari/v1/"
TIAGO_NAMESPACE = "https://gsi.upm.es/segb/robots/tiago/v1/"
DEFAULT_PUBLISH_URL = "http://localhost:5000"


@dataclass(slots=True)
class SimulationResult:
    """Artifacts generated by one demo interaction."""

    graph: Graph
    human_uri: URIRef
    shared_event_uri: URIRef
    ari_observation_uri: URIRef
    tiago_observation_uri: URIRef
    ari_response_uri: URIRef
    ari_namespace: str
    tiago_namespace: str


@dataclass(slots=True)
class PublishConfig:
    """Configuration used to publish demo logs to SEGB API."""

    base_url: str
    token: str | None = None
    user: str | None = None
    queue_file: str | None = None
    timeout_seconds: float = 20.0
    verify_tls: bool = True


def _build_loggers() -> tuple[Graph, SemanticSEGBLogger, SemanticSEGBLogger]:
    graph = Graph()
    policy = SharedEventPolicy(
        namespace="https://gsi.upm.es/segb/shared-events/",
        time_bucket_seconds=2,
    )
    ari_logger = SemanticSEGBLogger(
        base_namespace=ARI_NAMESPACE,
        robot_id="ari1",
        robot_name="ARI",
        graph=graph,
        shared_event_policy=policy,
    )
    tiago_logger = SemanticSEGBLogger(
        base_namespace=TIAGO_NAMESPACE,
        robot_id="tiago1",
        robot_name="TIAGo",
        graph=graph,
        shared_event_policy=policy,
    )
    return graph, ari_logger, tiago_logger


def run_simulation() -> SimulationResult:
    """Runs one clear interaction:
    - Maria speaks once.
    - ARI listens and answers.
    - TIAGo listens and does not answer.
    """
    graph, ari_logger, tiago_logger = _build_loggers()

    maria_uri = ari_logger.register_human("maria", first_name="Maria")

    text = "Could you show me climate news?"
    observed_at = datetime.now(timezone.utc)

    ari_result: AriMockResult = ari_handle_human_utterance(
        logger=ari_logger,
        human_uri=maria_uri,
        text=text,
        observed_at=observed_at,
    )
    tiago_result: TiagoMockResult = tiago_handle_human_utterance(
        logger=tiago_logger,
        human_uri=maria_uri,
        text=text,
        observed_at=observed_at,
    )

    if ari_result.shared_event_uri != tiago_result.shared_event_uri:
        raise RuntimeError("Shared context mismatch: ARI and TIAGo should resolve the same URI.")

    return SimulationResult(
        graph=graph,
        human_uri=maria_uri,
        shared_event_uri=ari_result.shared_event_uri,
        ari_observation_uri=ari_result.observation_message_uri,
        tiago_observation_uri=tiago_result.observation_message_uri,
        ari_response_uri=ari_result.response_message_uri,
        ari_namespace=ARI_NAMESPACE,
        tiago_namespace=TIAGO_NAMESPACE,
    )


def run_professional_ros2_mock_simulation() -> SimulationResult:
    """Backward-compatible alias kept for existing callers/tests."""
    return run_simulation()


def publish_simulation_result(simulation_result: SimulationResult, *, config: PublishConfig) -> dict[str, Any]:
    """Publishes the demo graph into SEGB backend."""
    publisher = SEGBPublisher(
        base_url=config.base_url,
        token=config.token,
        default_user=config.user,
        timeout_seconds=config.timeout_seconds,
        verify_tls=config.verify_tls,
        queue_file=config.queue_file,
    )
    publish_response = publisher.publish_graph(simulation_result.graph, user=config.user)
    return {
        "published": True,
        "publish_endpoint": f"{config.base_url.rstrip('/')}/ttl",
        "publish_response": publish_response,
        "graph_triplet_count": len(simulation_result.graph),
    }


def build_publish_config_from_args(args: argparse.Namespace) -> PublishConfig | None:
    """Builds PublishConfig from CLI args and environment variables."""
    base_url = args.publish_url or os.getenv("SEGB_API_URL") or DEFAULT_PUBLISH_URL
    if not base_url:
        return None

    token = args.token if args.token is not None else os.getenv("SEGB_API_TOKEN")
    user = args.user if args.user is not None else os.getenv("SEGB_LOG_USER")
    queue_file = args.queue_file if args.queue_file is not None else os.getenv("SEGB_QUEUE_FILE")
    timeout_env = os.getenv("SEGB_PUBLISH_TIMEOUT")
    timeout_seconds = args.timeout_seconds if args.timeout_seconds is not None else float(timeout_env or 20.0)
    verify_tls = not args.insecure

    return PublishConfig(
        base_url=base_url,
        token=token,
        user=user,
        queue_file=queue_file,
        timeout_seconds=timeout_seconds,
        verify_tls=verify_tls,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the simple ARI/TIAGo SEGB demo.")
    parser.add_argument(
        "--publish-url",
        default=None,
        help=f"SEGB API base URL (default: {DEFAULT_PUBLISH_URL}; env override: SEGB_API_URL).",
    )
    parser.add_argument("--token", default=None, help="Bearer token for API authentication (optional).")
    parser.add_argument("--user", default=None, help="Logical user to include in /ttl payload (optional).")
    parser.add_argument("--queue-file", default=None, help="Optional offline queue file for publication.")
    parser.add_argument("--timeout-seconds", type=float, default=None, help="HTTP timeout in seconds.")
    parser.add_argument("--insecure", action="store_true", help="Disable TLS certificate verification.")
    parser.add_argument("--no-print-ttl", action="store_true", help="Do not print TTL to stdout.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    result = run_simulation()

    publish_config = build_publish_config_from_args(args)
    if publish_config is not None:
        report = publish_simulation_result(result, config=publish_config)
        print(json.dumps(report, ensure_ascii=True, indent=2))

    if not args.no_print_ttl:
        print(f"SharedEvent URI: {result.shared_event_uri}")
        ttl = result.graph.serialize(format="turtle")
        print(ttl.decode("utf-8") if isinstance(ttl, bytes) else ttl)


if __name__ == "__main__":
    main()
