"""Advanced SEGB simulation for notebook reports with optional SEGB publication."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path

from rdflib import Graph

if __package__ is None or __package__ == "":
    # Script mode (`python examples/run_advanced_simulation.py`).
    project_root = Path(__file__).resolve().parents[1]
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))

    from examples.ari_mock import AriDetectionResult, AriMockResult, ari_detect_human_entry, ari_handle_human_utterance
    from examples.tiago_mock import TiagoDetectionResult, TiagoMockResult, tiago_detect_human_entry, tiago_handle_human_utterance
    from examples.run_simulation import (
        ARI_NAMESPACE,
        TIAGO_NAMESPACE,
        build_loggers,
        build_publish_config_from_args,
        publish_simulation_result,
        PublishConfig,
        SimulationResult,
    )
    from segb_logger import ActivityKind, EmotionScore, RobotStateSnapshot, SemanticSEGBLogger
    from segb_logger.namespaces import EMOML, ORO
else:
    # Module mode (`python -m examples.run_advanced_simulation`).
    from .ari_mock import AriDetectionResult, AriMockResult, ari_detect_human_entry, ari_handle_human_utterance
    from .tiago_mock import TiagoDetectionResult, TiagoMockResult, tiago_detect_human_entry, tiago_handle_human_utterance
    from .run_simulation import (
        ARI_NAMESPACE,
        TIAGO_NAMESPACE,
        build_loggers,
        build_publish_config_from_args,
        publish_simulation_result,
        PublishConfig,
        SimulationResult,
    )
    from segb_logger import ActivityKind, EmotionScore, RobotStateSnapshot, SemanticSEGBLogger
    from segb_logger.namespaces import EMOML, ORO


@dataclass(slots=True)
class AdvancedSimulationResult:
    """Artifacts generated by the advanced report-focused simulation."""

    graph: Graph
    base_result: SimulationResult
    base_timestamp: datetime


def _run_advanced_base_interaction() -> SimulationResult:
    """Runs the advanced scenario baseline without relying on `run_basic_simulation`."""
    graph, ari_logger, tiago_logger = build_loggers()

    maria_uri = ari_logger.register_human("maria", first_name="Maria")

    entry_observed_at = datetime.now(timezone.utc)
    speech_observed_at = entry_observed_at + timedelta(seconds=4)

    ari_entry_result: AriDetectionResult = ari_detect_human_entry(
        logger=ari_logger,
        human_uri=maria_uri,
        observed_at=entry_observed_at,
    )
    tiago_entry_result: TiagoDetectionResult = tiago_detect_human_entry(
        logger=tiago_logger,
        human_uri=maria_uri,
        observed_at=entry_observed_at,
    )

    if ari_entry_result.shared_event_uri != tiago_entry_result.shared_event_uri:
        raise RuntimeError("Shared context mismatch: ARI and TIAGo should resolve the same human-entry URI.")

    text = "ARI, me siento triste porque he recibido una mala noticia."

    ari_result: AriMockResult = ari_handle_human_utterance(
        logger=ari_logger,
        human_uri=maria_uri,
        text=text,
        observed_at=speech_observed_at,
    )
    tiago_result: TiagoMockResult = tiago_handle_human_utterance(
        logger=tiago_logger,
        human_uri=maria_uri,
        text=text,
        observed_at=speech_observed_at,
    )

    if ari_result.shared_event_uri != tiago_result.shared_event_uri:
        raise RuntimeError("Shared context mismatch: ARI and TIAGo should resolve the same URI.")

    return SimulationResult(
        graph=graph,
        human_uri=maria_uri,
        entry_shared_event_uri=ari_entry_result.shared_event_uri,
        shared_event_uri=ari_result.shared_event_uri,
        ari_observation_uri=ari_result.observation_message_uri,
        tiago_observation_uri=tiago_result.observation_message_uri,
        ari_response_uri=ari_result.response_message_uri,
        ari_namespace=ARI_NAMESPACE,
        tiago_namespace=TIAGO_NAMESPACE,
    )


def _enrich_notebook_ttl(base_result: SimulationResult) -> datetime:
    """Adds the same report-oriented TTL enrichment used in segb_reports_demo.ipynb."""
    ari_logger = SemanticSEGBLogger(
        base_namespace=ARI_NAMESPACE,
        robot_id="ari1",
        robot_name="ARI",
        graph=base_result.graph,
        namespace_prefix="ari",
        compact_resource_ids=True,
    )
    tiago_logger = SemanticSEGBLogger(
        base_namespace=TIAGO_NAMESPACE,
        robot_id="tiago1",
        robot_name="TIAGo",
        graph=base_result.graph,
        namespace_prefix="tiago",
        compact_resource_ids=True,
    )

    human_uri = base_result.human_uri

    asr_model = ari_logger.register_ml_model("asr_vosk_es", label="ASR Vosk ES", version="0.3")
    emotion_model = ari_logger.register_ml_model("emotion_big6_v1", label="Emotion Big6 CNN", version="1.0")
    vision_model = ari_logger.register_ml_model(
        "vision_human_detector_v1",
        label="Human Detector",
        version="2.1",
    )

    ari_listening_activity = ari_logger.resource_uri("activity", "ari_listening_1")
    ari_logger.link_activity_model(ari_listening_activity, asr_model)

    ari_logger.log_activity(
        activity_id="vision_perception_1",
        activity_kind=ActivityKind.HUMAN_DETECTION,
        started_at=datetime.now(timezone.utc),
        ended_at=datetime.now(timezone.utc),
        used_models=[vision_model],
        related_shared_events=[base_result.shared_event_uri],
    )

    dataset_uri = ari_logger.register_dataset("emotion_dataset_v1", label="EmotionDataset v1")
    eval_uri = ari_logger.register_model_evaluation(
        "emotion_accuracy_eval_1",
        value=0.89,
    )

    train_run = ari_logger.log_activity(
        activity_id="emotion_model_training_run_1",
        activity_kind=ActivityKind.ML_RUN,
        started_at=datetime.now(timezone.utc) - timedelta(minutes=30),
        ended_at=datetime.now(timezone.utc) - timedelta(minutes=20),
        used_models=[emotion_model],
        used_entities=[dataset_uri],
        produced_entity_results=[emotion_model, eval_uri],
    )
    ari_logger.link_ml_run_input(train_run, dataset_uri)
    ari_logger.link_ml_run_output(train_run, emotion_model)
    ari_logger.link_ml_run_output(train_run, eval_uri)

    base_t = datetime.now(timezone.utc) - timedelta(minutes=10)

    cheer_request_shared_event = ari_logger.get_shared_event_uri(
        event_kind="human_utterance",
        observed_at=base_t,
        subject=human_uri,
        text="ARI, can you show me a piece of news to cheer me up?",
        modality="speech",
    )

    cheer_request_listening_activity = ari_logger.log_activity(
        activity_id="ari_listening_cheer_request_1",
        activity_kind=ActivityKind.LISTENING,
        started_at=base_t,
        ended_at=base_t + timedelta(seconds=5),
        triggered_by_activity=ari_listening_activity,
        triggered_by_entity=base_result.ari_response_uri,
        related_shared_events=[cheer_request_shared_event],
        used_entities=[base_result.ari_response_uri],
        used_models=[asr_model],
    )
    cheer_request_message = ari_logger.log_message(
        "ARI, can you show me some news to cheer me up?",
        message_id="ari_heard_cheer_request_1",
        generated_by_activity=cheer_request_listening_activity,
        message_types=[ORO.InitialMessage],
        language="en",
        previous_message=base_result.ari_response_uri,
    )
    ari_logger.link_observation_to_shared_event(cheer_request_message, cheer_request_shared_event, confidence=0.95)

    exam_news_activity = ari_logger.log_activity(
        activity_id="ari_exam_news_response_1",
        activity_kind=ActivityKind.RESPONSE,
        started_at=base_t + timedelta(seconds=10),
        ended_at=base_t + timedelta(seconds=15),
        triggered_by_activity=cheer_request_listening_activity,
        triggered_by_entity=cheer_request_message,
        related_shared_events=[cheer_request_shared_event],
        used_entities=[cheer_request_message],
    )
    exam_news_message = ari_logger.log_message(
        "Here is one headline: many students are anxious because an important exam is coming soon.",
        message_id="ari_exam_news_msg_1",
        generated_by_activity=exam_news_activity,
        message_types=[ORO.ResponseMessage],
        previous_message=cheer_request_message,
    )

    anxiety_face_observation = ari_logger.log_observation(
        observation_id="ari_face_anxiety_after_exam_1",
        label="Face snapshot after exam news",
        related_shared_event=cheer_request_shared_event,
        confidence=0.93,
        mark_as_result=True,
    )

    anxiety_activity = ari_logger.log_activity(
        activity_id="emotion_analysis_1",
        activity_kind=ActivityKind.EMOTION_ANALYSIS,
        extra_types=[ORO.EmotionRecognitionEvent],
        label="Maria anxiety detected after exam news",
        started_at=base_t + timedelta(minutes=1),
        ended_at=base_t + timedelta(minutes=1, seconds=5),
        used_models=[emotion_model],
        related_shared_events=[cheer_request_shared_event],
        triggered_by_entity=anxiety_face_observation,
        used_entities=[anxiety_face_observation],
    )
    ari_logger.log_emotion_annotation(
        source_activity=anxiety_activity,
        targets=[human_uri, ari_logger.robot_uri],
        emotions=[
            EmotionScore(
                category=EMOML.big6_fear,
                intensity=0.90,
                confidence=0.95,
            ),
        ],
        emotion_model=EMOML.big6,
    )

    apology_activity = ari_logger.log_activity(
        activity_id="ari_apology_response_1",
        activity_kind=ActivityKind.RESPONSE,
        started_at=base_t + timedelta(minutes=2),
        ended_at=base_t + timedelta(minutes=2, seconds=5),
        triggered_by_activity=anxiety_activity,
        triggered_by_entity=anxiety_face_observation,
        related_shared_events=[cheer_request_shared_event],
        used_entities=[anxiety_face_observation],
    )
    apology_message = ari_logger.log_message(
        "I am sorry, Maria. That exam news was not a good choice right now.",
        message_id="ari_apology_msg_1",
        generated_by_activity=apology_activity,
        message_types=[ORO.ResponseMessage],
        previous_message=exam_news_message,
    )

    animal_news_activity = ari_logger.log_activity(
        activity_id="ari_animal_news_response_1",
        activity_kind=ActivityKind.RESPONSE,
        started_at=base_t + timedelta(minutes=2, seconds=20),
        ended_at=base_t + timedelta(minutes=2, seconds=25),
        triggered_by_activity=apology_activity,
        triggered_by_entity=apology_message,
        related_shared_events=[cheer_request_shared_event],
        used_entities=[apology_message],
    )
    animal_news_message = ari_logger.log_message(
        "Here is another one: a rescue center found homes for twenty puppies this weekend.",
        message_id="ari_animal_news_msg_1",
        generated_by_activity=animal_news_activity,
        message_types=[ORO.ResponseMessage],
        previous_message=apology_message,
    )

    gratitude_listening_activity = ari_logger.log_activity(
        activity_id="ari_listening_gratitude_1",
        activity_kind=ActivityKind.LISTENING,
        started_at=base_t + timedelta(minutes=3),
        ended_at=base_t + timedelta(minutes=3, seconds=5),
        triggered_by_activity=animal_news_activity,
        triggered_by_entity=animal_news_message,
        related_shared_events=[cheer_request_shared_event],
        used_entities=[animal_news_message],
        used_models=[asr_model],
    )
    gratitude_message = ari_logger.log_message(
        "Thank you, ARI! That animal news made me very happy.",
        message_id="ari_heard_gratitude_1",
        generated_by_activity=gratitude_listening_activity,
        message_types=[ORO.InitialMessage],
        language="en",
        previous_message=animal_news_message,
    )
    ari_logger.link_observation_to_shared_event(gratitude_message, cheer_request_shared_event, confidence=0.97)

    very_happy_face_observation = ari_logger.log_observation(
        observation_id="ari_face_very_happy_1",
        label="Face snapshot after animal news",
        related_shared_event=cheer_request_shared_event,
        confidence=0.96,
        mark_as_result=True,
    )

    very_happy_activity = ari_logger.log_activity(
        activity_id="emotion_analysis_2",
        activity_kind=ActivityKind.EMOTION_ANALYSIS,
        extra_types=[ORO.EmotionRecognitionEvent],
        label="Maria very happy after animal news",
        started_at=base_t + timedelta(minutes=4),
        ended_at=base_t + timedelta(minutes=4, seconds=5),
        used_models=[emotion_model],
        related_shared_events=[cheer_request_shared_event],
        triggered_by_activity=gratitude_listening_activity,
        triggered_by_entity=very_happy_face_observation,
        used_entities=[very_happy_face_observation],
    )
    ari_logger.log_emotion_annotation(
        source_activity=very_happy_activity,
        targets=[human_uri, ari_logger.robot_uri],
        emotions=[
            EmotionScore(
                category=EMOML.big6_happiness,
                intensity=0.98,
                confidence=0.96,
            ),
        ],
        emotion_model=EMOML.big6,
    )

    room_a = ari_logger.resource_uri("location", "room_a")
    room_b = ari_logger.resource_uri("location", "room_b")
    room_c = ari_logger.resource_uri("location", "room_c")

    ari_logger.log_robot_state(
        RobotStateSnapshot(
            timestamp=base_t + timedelta(minutes=1),
            location=room_a,
            battery_level=0.82,
            mission_phase="listen",
        ),
        state_id="ari_state_1",
    )
    ari_logger.log_robot_state(
        RobotStateSnapshot(
            timestamp=base_t + timedelta(minutes=3),
            location=room_b,
            battery_level=0.79,
            mission_phase="respond",
        ),
        state_id="ari_state_2",
    )
    tiago_logger.log_robot_state(
        RobotStateSnapshot(
            timestamp=base_t + timedelta(minutes=1),
            location=room_b,
            battery_level=0.74,
            mission_phase="listen",
        ),
        state_id="tiago_state_1",
    )
    tiago_logger.log_robot_state(
        RobotStateSnapshot(
            timestamp=base_t + timedelta(minutes=4),
            location=room_c,
            battery_level=0.72,
            mission_phase="idle",
        ),
        state_id="tiago_state_2",
    )

    return base_t


def run_advanced_simulation() -> AdvancedSimulationResult:
    """Runs an independent advanced simulation and enriches it with report-oriented TTL."""
    base_result = _run_advanced_base_interaction()
    base_timestamp = _enrich_notebook_ttl(base_result)
    return AdvancedSimulationResult(
        graph=base_result.graph,
        base_result=base_result,
        base_timestamp=base_timestamp,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the advanced SEGB simulation, generate Turtle, and optionally publish to SEGB."
    )
    parser.add_argument("--ttl-output", default=None, help="Optional output path to write generated Turtle.")
    parser.add_argument("--publish-url", default=None, help="SEGB API base URL (optional).")
    parser.add_argument("--token", default=None, help="Bearer token for API authentication (optional).")
    parser.add_argument("--user", default=None, help="Logical user to include in /ttl payload (optional).")
    parser.add_argument("--queue-file", default=None, help="Optional offline queue file for publication.")
    parser.add_argument("--timeout-seconds", type=float, default=None, help="HTTP timeout in seconds.")
    parser.add_argument("--insecure", action="store_true", help="Disable TLS certificate verification.")
    parser.add_argument("--no-publish", action="store_true", help="Do not publish generated TTL to SEGB API.")
    parser.add_argument("--no-print-ttl", action="store_true", help="Do not print generated Turtle to stdout.")
    return parser.parse_args()


def publish_advanced_simulation_result(
    simulation_result: AdvancedSimulationResult,
    *,
    config: PublishConfig,
) -> dict[str, object]:
    """Publishes advanced simulation graph into SEGB backend."""
    return publish_simulation_result(simulation_result.base_result, config=config)


def main() -> None:
    args = parse_args()
    result = run_advanced_simulation()

    if not args.no_publish:
        publish_config = build_publish_config_from_args(args)
        if publish_config is not None:
            report = publish_advanced_simulation_result(result, config=publish_config)
            print(json.dumps(report, ensure_ascii=True, indent=2))

    ttl = result.graph.serialize(format="turtle")
    ttl_text = ttl.decode("utf-8") if isinstance(ttl, bytes) else ttl

    if args.ttl_output:
        output_path = Path(args.ttl_output).expanduser()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(ttl_text, encoding="utf-8")
        print(f"Wrote Turtle to: {output_path}")

    print(f"SharedEvent URI: {result.base_result.shared_event_uri}")
    print(f"Triples generated: {len(result.graph)}")

    if not args.no_print_ttl:
        print(ttl_text)


if __name__ == "__main__":
    main()
