"""Advanced SEGB simulation for notebook reports with optional SEGB publication."""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path

from rdflib import Graph, Literal
from rdflib.namespace import RDF, RDFS, XSD

if __package__ is None or __package__ == "":
    # Script mode (`python examples/run_advanced_simulation.py`).
    project_root = Path(__file__).resolve().parents[1]
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))

    from examples.run_simulation import (
        ARI_NAMESPACE,
        TIAGO_NAMESPACE,
        build_publish_config_from_args,
        publish_simulation_result,
        PublishConfig,
        SimulationResult,
        run_simulation,
    )
    from segb_logger import ActivityKind, EmotionScore, RobotStateSnapshot, SemanticSEGBLogger
    from segb_logger.namespaces import EMOML, MLS, SEGB
else:
    # Module mode (`python -m examples.run_advanced_simulation`).
    from .run_simulation import (
        ARI_NAMESPACE,
        TIAGO_NAMESPACE,
        build_publish_config_from_args,
        publish_simulation_result,
        PublishConfig,
        SimulationResult,
        run_simulation,
    )
    from segb_logger import ActivityKind, EmotionScore, RobotStateSnapshot, SemanticSEGBLogger
    from segb_logger.namespaces import EMOML, MLS, SEGB


@dataclass(slots=True)
class AdvancedSimulationResult:
    """Artifacts generated by the advanced report-focused simulation."""

    graph: Graph
    base_result: SimulationResult
    base_timestamp: datetime


def _enrich_notebook_ttl(base_result: SimulationResult) -> datetime:
    """Adds the same report-oriented TTL enrichment used in segb_reports_demo.ipynb."""
    graph = base_result.graph

    ari_logger = SemanticSEGBLogger(
        base_namespace=ARI_NAMESPACE,
        robot_id="ari1",
        robot_name="ARI",
        graph=graph,
    )
    tiago_logger = SemanticSEGBLogger(
        base_namespace=TIAGO_NAMESPACE,
        robot_id="tiago1",
        robot_name="TIAGo",
        graph=graph,
    )

    human_uri = base_result.human_uri

    asr_model = ari_logger.register_ml_model("asr_vosk_es", label="ASR Vosk ES", version="0.3")
    emotion_model = ari_logger.register_ml_model("emotion_big6_v1", label="Emotion Big6 CNN", version="1.0")
    vision_model = ari_logger.register_ml_model(
        "vision_human_detector_v1",
        label="Human Detector",
        version="2.1",
    )

    ari_listening_activity = ari_logger.resolve_term(f"{ARI_NAMESPACE}activity/ari_listening_1")
    graph.add((ari_listening_activity, SEGB.usedMLModel, asr_model))

    ari_logger.log_activity(
        activity_id="vision_perception_1",
        activity_kind=ActivityKind.HUMAN_DETECTION,
        started_at=datetime.now(timezone.utc),
        ended_at=datetime.now(timezone.utc),
        used_models=[vision_model],
        related_shared_events=[base_result.shared_event_uri],
    )

    dataset_uri = ari_logger.resource_uri("dataset", "emotion_dataset_v1")
    graph.add((dataset_uri, RDF.type, MLS.Dataset))
    graph.add((dataset_uri, RDFS.label, Literal("EmotionDataset v1")))

    eval_uri = ari_logger.resource_uri("model-eval", "emotion_accuracy_eval_1")
    graph.add((eval_uri, RDF.type, MLS.ModelEvaluation))
    graph.add((eval_uri, MLS.hasValue, Literal(0.89, datatype=XSD.double)))

    train_run = ari_logger.log_activity(
        activity_id="emotion_model_training_run_1",
        activity_kind=ActivityKind.ML_RUN,
        started_at=datetime.now(timezone.utc) - timedelta(minutes=30),
        ended_at=datetime.now(timezone.utc) - timedelta(minutes=20),
        used_models=[emotion_model],
        produced_entity_results=[emotion_model, eval_uri],
    )
    graph.add((train_run, MLS.hasInput, dataset_uri))
    graph.add((train_run, MLS.hasOutput, emotion_model))
    graph.add((train_run, MLS.hasOutput, eval_uri))

    base_t = datetime.now(timezone.utc) - timedelta(minutes=10)

    news_summary_activity = ari_logger.log_activity(
        activity_id="ari_news_summary_1",
        activity_kind=ActivityKind.RESPONSE,
        started_at=base_t,
        ended_at=base_t + timedelta(seconds=5),
        triggered_by_activity=ari_listening_activity,
        triggered_by_entity=base_result.ari_observation_uri,
        related_shared_events=[base_result.shared_event_uri],
        used_entities=[base_result.ari_observation_uri],
    )
    news_summary_message = ari_logger.log_message(
        "Climate update: heat waves are increasing and local air quality worsened this week.",
        message_id="ari_news_summary_msg_1",
        generated_by_activity=news_summary_activity,
        message_types=["oro:ResponseMessage"],
        previous_message=base_result.ari_response_uri,
    )

    support_activity = ari_logger.log_activity(
        activity_id="ari_support_plan_1",
        activity_kind=ActivityKind.RESPONSE,
        started_at=base_t + timedelta(minutes=6),
        ended_at=base_t + timedelta(minutes=6, seconds=5),
        triggered_by_activity=news_summary_activity,
        triggered_by_entity=news_summary_message,
        used_entities=[news_summary_message],
    )
    support_message = ari_logger.log_message(
        "I can show you practical protection tips and schedule reminders for tomorrow.",
        message_id="ari_support_plan_msg_1",
        generated_by_activity=support_activity,
        message_types=["oro:ResponseMessage"],
        previous_message=news_summary_message,
    )

    emotion_timeline = [
        {
            "category": EMOML.big6_surprise,
            "intensity": 0.42,
            "confidence": 0.91,
            "trigger_entity": base_result.ari_observation_uri,
            "note": "Maria notices both robots detected her request quickly.",
        },
        {
            "category": EMOML.big6_fear,
            "intensity": 0.86,
            "confidence": 0.93,
            "trigger_entity": news_summary_message,
            "note": "Maria reacts with fear after hearing about stronger heat waves.",
        },
        {
            "category": EMOML.big6_sadness,
            "intensity": 0.79,
            "confidence": 0.92,
            "trigger_entity": news_summary_message,
            "note": "Maria feels sadness when impacts on vulnerable people are mentioned.",
        },
        {
            "category": EMOML.big6_disgust,
            "intensity": 0.56,
            "confidence": 0.89,
            "trigger_entity": news_summary_message,
            "note": "Maria shows disgust toward pollution sources discussed in the update.",
        },
        {
            "category": EMOML.big6_anger,
            "intensity": 0.82,
            "confidence": 0.90,
            "trigger_entity": news_summary_message,
            "note": "Maria becomes angry about perceived lack of action.",
        },
        {
            "category": EMOML.big6_happiness,
            "intensity": 0.60,
            "confidence": 0.90,
            "trigger_entity": support_message,
            "note": "Maria ends with relief and positive affect after receiving concrete help.",
        },
    ]

    for index, item in enumerate(emotion_timeline, start=1):
        emotion_activity = ari_logger.log_activity(
            activity_id=f"emotion_analysis_{index}",
            activity_kind=ActivityKind.EMOTION_ANALYSIS,
            extra_types=["oro:EmotionRecognitionEvent"],
            label=f"Maria emotion snapshot {index}",
            started_at=base_t + timedelta(minutes=index),
            ended_at=base_t + timedelta(minutes=index, seconds=5),
            used_models=[emotion_model],
            related_shared_events=[base_result.shared_event_uri],
            triggered_by_entity=item["trigger_entity"],
            used_entities=[item["trigger_entity"]],
        )
        graph.add((emotion_activity, RDFS.comment, Literal(item["note"], lang="en")))
        ari_logger.log_emotion_annotation(
            source_activity=emotion_activity,
            targets=[human_uri, ari_logger.robot_uri],
            emotions=[
                EmotionScore(
                    category=item["category"],
                    intensity=item["intensity"],
                    confidence=item["confidence"],
                ),
            ],
            emotion_model=EMOML.big6,
        )

    room_a = ari_logger.resource_uri("location", "room_a")
    room_b = ari_logger.resource_uri("location", "room_b")
    room_c = ari_logger.resource_uri("location", "room_c")

    ari_logger.log_robot_state(
        RobotStateSnapshot(
            timestamp=base_t + timedelta(minutes=1),
            location=room_a,
            battery_level=0.82,
            mission_phase="listen",
        ),
        state_id="ari_state_1",
    )
    ari_logger.log_robot_state(
        RobotStateSnapshot(
            timestamp=base_t + timedelta(minutes=3),
            location=room_b,
            battery_level=0.79,
            mission_phase="respond",
        ),
        state_id="ari_state_2",
    )
    tiago_logger.log_robot_state(
        RobotStateSnapshot(
            timestamp=base_t + timedelta(minutes=1),
            location=room_b,
            battery_level=0.74,
            mission_phase="listen",
        ),
        state_id="tiago_state_1",
    )
    tiago_logger.log_robot_state(
        RobotStateSnapshot(
            timestamp=base_t + timedelta(minutes=4),
            location=room_c,
            battery_level=0.72,
            mission_phase="idle",
        ),
        state_id="tiago_state_2",
    )

    return base_t


def run_advanced_simulation() -> AdvancedSimulationResult:
    """Runs base simulation and enriches it with report-oriented TTL."""
    base_result = run_simulation()
    base_timestamp = _enrich_notebook_ttl(base_result)
    return AdvancedSimulationResult(
        graph=base_result.graph,
        base_result=base_result,
        base_timestamp=base_timestamp,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the advanced SEGB simulation, generate Turtle, and optionally publish to SEGB."
    )
    parser.add_argument("--ttl-output", default=None, help="Optional output path to write generated Turtle.")
    parser.add_argument("--publish-url", default=None, help="SEGB API base URL (optional).")
    parser.add_argument("--token", default=None, help="Bearer token for API authentication (optional).")
    parser.add_argument("--user", default=None, help="Logical user to include in /ttl payload (optional).")
    parser.add_argument("--queue-file", default=None, help="Optional offline queue file for publication.")
    parser.add_argument("--timeout-seconds", type=float, default=None, help="HTTP timeout in seconds.")
    parser.add_argument("--insecure", action="store_true", help="Disable TLS certificate verification.")
    parser.add_argument("--no-publish", action="store_true", help="Do not publish generated TTL to SEGB API.")
    parser.add_argument("--no-print-ttl", action="store_true", help="Do not print generated Turtle to stdout.")
    return parser.parse_args()


def publish_advanced_simulation_result(
    simulation_result: AdvancedSimulationResult,
    *,
    config: PublishConfig,
) -> dict[str, object]:
    """Publishes advanced simulation graph into SEGB backend."""
    return publish_simulation_result(simulation_result.base_result, config=config)


def main() -> None:
    args = parse_args()
    result = run_advanced_simulation()

    if not args.no_publish:
        publish_config = build_publish_config_from_args(args)
        if publish_config is not None:
            report = publish_advanced_simulation_result(result, config=publish_config)
            print(json.dumps(report, ensure_ascii=True, indent=2))

    ttl = result.graph.serialize(format="turtle")
    ttl_text = ttl.decode("utf-8") if isinstance(ttl, bytes) else ttl

    if args.ttl_output:
        output_path = Path(args.ttl_output).expanduser()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(ttl_text, encoding="utf-8")
        print(f"Wrote Turtle to: {output_path}")

    print(f"SharedEvent URI: {result.base_result.shared_event_uri}")
    print(f"Triples generated: {len(result.graph)}")

    if not args.no_print_ttl:
        print(ttl_text)


if __name__ == "__main__":
    main()
