"""Very small TIAGo mock for the public SEGB demo."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone

from rdflib import URIRef

from segb_logger import ActivityKind, SemanticSEGBLogger


@dataclass(slots=True)
class TiagoMockResult:
    """Semantic artifacts generated by TIAGo for one human utterance."""

    shared_event_uri: URIRef
    listening_activity_uri: URIRef
    observation_message_uri: URIRef


def tiago_handle_human_utterance(
    *,
    logger: SemanticSEGBLogger,
    human_uri: URIRef,
    text: str,
    observed_at: datetime,
) -> TiagoMockResult:
    """Logs TIAGo behavior: listen only (no response)."""
    shared_event_uri = logger.get_shared_event_uri(
        event_kind="human_utterance",
        observed_at=observed_at,
        subject=human_uri,
        text=text,
        modality="speech",
    )

    listening_activity_uri = logger.log_activity(
        activity_id="tiago_listening_1",
        activity_kind=ActivityKind.LISTENING,
        started_at=observed_at,
        ended_at=datetime.now(timezone.utc),
        related_shared_events=[shared_event_uri],
    )
    observation_message_uri = logger.log_message(
        text,
        message_id="tiago_heard_1",
        generated_by_activity=listening_activity_uri,
        message_types=["oro:InitialMessage"],
    )
    logger.link_observation_to_shared_event(observation_message_uri, shared_event_uri, confidence=0.90)

    return TiagoMockResult(
        shared_event_uri=shared_event_uri,
        listening_activity_uri=listening_activity_uri,
        observation_message_uri=observation_message_uri,
    )
